export const PRODUCTS = [
  {
    name: "curry",
    category: "Food",
    price: "20.000",
    productImg: require("../Img/katsu.jpg"),
  },
  {
    name: "katsu",
    category: "Food",
    price: "20.000",
    productImg: require("../Img/curry.jpg"),
  },
  {
    name: "ayam geprek",
    category: "Food",
    price: "25.000",
    productImg: require("../Img/curry.jpg"),
  },
  {
    name: "Thai tea",
    category: "Drink",
    price: "25.000",
    productImg: require("../Img/katsu.jpg"),
  },
  {
    name: "Jus mangga",
    category: "Drink",
    price: "10.000",
    productImg: require("../Img/curry.jpg"),
  },
  {
    name: "Jus sirsak",
    category: "Drink",
    price: "10.000",
    productImg: require("../Img/katsu.jpg"),
  },
  {
    name: "boba",
    category: "Drink",
    price: "18.000",
    productImg: require("../Img/curry.jpg"),
  },
  {
    name: "milkshake",
    category: "Drink",
    price: "18.000",
    productImg: require("../Img/katsu.jpg"),
  },
  {
    name: "Kebab",
    category: "Snack",
    price: "15.000",
    productImg: require("../Img/curry.jpg"),
  },
  {
    name: "Mojito",
    category: "Drink",
    price: "20.000",
    productImg: require("../Img/katsu.jpg"),
  },
  {
    name: "Es coklat roti",
    category: "Drink",
    price: "10.000",
    productImg: require("../Img/curry.jpg"),
  },
  {
    name: "Churros",
    category: "Snack",
    price: "10.000",
    productImg: require("../Img/katsu.jpg"),
  },
  {
    name: "Burger",
    category: "Snack",
    price: "10.000",
    productImg: require("../Img/curry.jpg"),
  },
];
